name: Trigger Jenkins Build

on:
  push:
    branches: [ "main" ]

jobs:
  trigger:
    runs-on: [self-hosted, delphi]

    steps:
    - name: Trigger Jenkins via REST API
      env:
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        REPO_NAME: ${{ github.repository }}
      run: |
        echo "Triggering Jenkins for $REPO_NAME..."
        curl -X POST \
          -u "$JENKINS_USER:$JENKINS_TOKEN" \
          "http://jenkins.internal:8080/job/${REPO_NAME}/build?delay=0sec"
