name: Trigger Jenkins Build

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Application name (e.g., GGU-CONNECT, GGU-RETAIN)'
        required: true
        type: string
      version:
        description: 'Version number (e.g., 1.46, 4.8.1.2)'
        required: true
        type: string
      skip_approval:
        description: 'Skip manual approval step'
        required: false
        type: boolean
        default: false

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Jenkins Build
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          # Check required environment variables
          if [ -z "$JENKINS_URL" ] || [ -z "$JENKINS_USER" ] || [ -z "$JENKINS_TOKEN" ]; then
            echo "Error: Required Jenkins secrets are not configured"
            echo "Please configure the following organization secrets:"
            echo "  - JENKINS_URL"
            echo "  - JENKINS_USER"
            echo "  - JENKINS_TOKEN"
            exit 1
          fi

          # Prepare skip approval flag
          SKIP_APPROVAL_FLAG=""
          if [ "${{ github.event.inputs.skip_approval }}" = "true" ]; then
            SKIP_APPROVAL_FLAG="--skip-approval"
          fi

          # Make script executable
          chmod +x ./infra/ggu-build-management/scripts/trigger-jenkins-build.sh

          # Trigger Jenkins build
          ./infra/ggu-build-management/scripts/trigger-jenkins-build.sh \
            --non-interactive \
            --app "${{ github.event.inputs.app_name }}" \
            --version "${{ github.event.inputs.version }}" \
            $SKIP_APPROVAL_FLAG

      - name: Summary
        if: success()
        run: |
          echo "## Jenkins Build Triggered Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Application:** ${{ github.event.inputs.app_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Skip Approval:** ${{ github.event.inputs.skip_approval }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check Jenkins UI for build progress: ${JENKINS_URL}" >> $GITHUB_STEP_SUMMARY
